### ISSUE TITLE
ReflectionCommon throws exception for EF Core 2.1

### ISSUE THREAD

**Issue by Scandal-UK** [PomeloFoundation/Lolita#19]
This extension appears to throw an exception whenever it is used with EF Core 2.1 - I am using "v2.1.0-rc1-final" of Pomelo EntityFrameworkCore MySql.

```
System.TypeInitializationException: The type initializer for 'Pomelo.EntityFrameworkCore.Lolita.ReflectionCommon' threw an exception. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Pomelo.EntityFrameworkCore.Lolita.ReflectionCommon..cctor()
```

**Comment by toralux** [comment]
Do anyone have a solution for 2.1/2.1.1? Or should I revert to 2.0?

**Comment by Scandal-UK** [comment]
The last commit for this project was November 2017. I have removed Lolita from my projects as it is no longer maintained - I have replaced it with calls to ExecuteSqlCommandAsync, which is likely to continue working going forwards.
